### ISSUE TITLE
RC Configuration File

### ISSUE THREAD

**Issue by femoral** [femoral/packetizr#21]
- Should load default argument values from .packetizrrc

**example:** 
```yaml
gen:
  lang: "csharp"
  out: "./packets"
  params: 
    namespacePrefix: "Project.Networking.Packets"
```
