### ISSUE TITLE
Object Types

### ISSUE THREAD

**Issue by femoral** [femoral/packetizr#9]
- Should be able to define list types in a OAS like fashion:

```yaml
packets:
  - header: 1
    name: ObjectMessage
    fields:
      objectField:
        type: object
        schema: TestObject
components:
  schemas:
    TestObject:
      id:
        type: int32
      name:
        type: char
        length: 10
```

- Should throw an error if circular references are detected
